import { useState } from 'react';
import { Modal } from '../ui/Modal';
import { Button } from '../ui/Button';
import { useDocuments } from '../../contexts/DocumentContext';
import { format } from 'date-fns';
import { Copy, Download, FileText, CheckCircle } from 'lucide-react';
import { formatDate } from '../../utils/formatters';

interface ExportPanelProps {
  isOpen: boolean;
  onClose: () => void;
}

export function ExportPanel({ isOpen, onClose }: ExportPanelProps) {
  const { getDailySummary, state } = useDocuments();
  const [copied, setCopied] = useState(false);
  
  const today = new Date().toISOString().split('T')[0];
  const summary = getDailySummary(today);
  
  // Calculate additional metrics
  const criticalDocs = state.documents.filter(d => d.priority === 'critical');
  const escalatedDocs = state.documents.filter(d => d.status === 'escalated');
  const unassignedDocs = state.documents.filter(d => !d.assignee);

  const reportText = `CLEAR DESK - DAILY SUMMARY REPORT
Generated: ${format(new Date(), 'MMM d, yyyy h:mm a')}

=== DOCUMENT OVERVIEW ===
Total Documents: ${summary.totalDocuments}
Pending: ${summary.pendingCount}
Processed Today: ${summary.processedCount}
Escalated: ${summary.escalatedCount}
Critical Priority: ${summary.criticalCount}

=== BY DOCUMENT TYPE ===
${Object.entries(summary.byType).map(([type, count]) => `  ${type}: ${count}`).join('\n') || '  No documents'}

=== BY ASSIGNEE ===
${Object.entries(summary.byAssignee).map(([name, count]) => `  ${name}: ${count}`).join('\n') || '  No assignments'}

=== CRITICAL ITEMS REQUIRING ATTENTION ===
${criticalDocs.length > 0 
  ? criticalDocs.map(d => `  • ${d.originalName} - ${d.extractedData?.customerName || 'Unknown'} - ${d.extractedData?.amount ? '$' + d.extractedData.amount.toLocaleString() : 'No amount'}`).join('\n')
  : '  No critical items'}

=== ESCALATED DOCUMENTS ===
${escalatedDocs.length > 0
  ? escalatedDocs.map(d => `  • ${d.originalName} - ${d.escalationReasons?.map(r => r.description).join(', ') || 'No reason given'}`).join('\n')
  : '  No escalated documents'}

=== UNASSIGNED DOCUMENTS ===
${unassignedDocs.length > 0
  ? unassignedDocs.map(d => `  • ${d.originalName}`).join('\n')
  : '  All documents assigned'}

=== NOTES ===
Generated by ClearDesk AI Document Processing System
For internal use only`;

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(reportText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const handleDownload = () => {
    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `clear-desk-summary-${today}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Daily Summary Report" size="lg">
      <div className="space-y-6">
        {/* Summary Cards */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div className="bg-blue-50 rounded-lg p-4 text-center">
            <p className="text-2xl font-bold text-blue-600">{summary.totalDocuments}</p>
            <p className="text-sm text-blue-700">Total Documents</p>
          </div>
          <div className="bg-green-50 rounded-lg p-4 text-center">
            <p className="text-2xl font-bold text-green-600">{summary.processedCount}</p>
            <p className="text-sm text-green-700">Processed</p>
          </div>
          <div className="bg-yellow-50 rounded-lg p-4 text-center">
            <p className="text-2xl font-bold text-yellow-600">{summary.pendingCount}</p>
            <p className="text-sm text-yellow-700">Pending</p>
          </div>
          <div className="bg-red-50 rounded-lg p-4 text-center">
            <p className="text-2xl font-bold text-red-600">{summary.escalatedCount}</p>
            <p className="text-sm text-red-700">Escalated</p>
          </div>
        </div>

        {/* Report Preview */}
        <div>
          <div className="flex items-center justify-between mb-2">
            <h4 className="text-sm font-medium text-gray-700 flex items-center">
              <FileText className="w-4 h-4 mr-2" />
              Report Preview
            </h4>
            <span className="text-xs text-gray-500">
              {formatDate(today)}
            </span>
          </div>
          <div className="bg-gray-50 border border-gray-200 rounded-lg p-4 max-h-64 overflow-y-auto">
            <pre className="text-xs text-gray-700 whitespace-pre-wrap font-mono">
              {reportText}
            </pre>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-col sm:flex-row gap-3 pt-4 border-t border-gray-200">
          <Button
            variant="secondary"
            onClick={handleCopy}
            leftIcon={copied ? <CheckCircle className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
            className="flex-1"
          >
            {copied ? 'Copied!' : 'Copy to Clipboard'}
          </Button>
          <Button
            variant="primary"
            onClick={handleDownload}
            leftIcon={<Download className="w-4 h-4" />}
            className="flex-1"
          >
            Download Report
          </Button>
        </div>
      </div>
    </Modal>
  );
}
